---
version: "1"
rules:
  - base: master
    upstream: nelhage:master
    mergeMethod: rebase
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
  - base: debian
    upstream: nelhage:debian
    mergeMethod: rebase
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
