---
enabled: true
auto: false
remote_files: []
comments: true
statuses:
  differences: true
  no-differences: false
  error: true
request_review:
  origin: author|owner
  forked: author|owner
labels: []
restylers:
  - astyle
  - prettier
  - shfmt
